version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/rest-api-server
permissions:
  - object: /home/ec2-user/rest-api-server
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  ApplicationStop:
    - location: scripts/application_stop.sh
      runas: ec2-user
  BeforeInstall:
    - location: scripts/clean_instance.sh
      runas: root
  AfterInstall:
    - location: scripts/migrate.sh
      runas: ec2-user
  # ApplicationStart:
  #   - location: scripts/start_application.sh
  #     runas: ec2-user
