version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.1
    working_directory: /home/circleci/project/rest_api_project
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: chown site-packages, usr/bin
          command: |
          sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages/
          sudo chown -R circleci:circleci /usr/local/bin
      - run:
          name: pip install
          command: |
            pip install -r requirements.txt
      - run:
          name: run test
          command: |
            . venv/bin/activate
            python manage.py test rest_api_app.tests

      - store_artifacts:
          path: test-reports
          destination: test-reports

  deploy:
    working_directory: ~/repo
    environment:
      - AWS_DEFAULT_REGION: ap-northeast-1
      - CODE_DEPLOY_S3_BUCKET_NAME: rest-api-server
      - CODE_DEPLOY_APPLICATION_NAME: rest-api-server
      - CODE_DEPLOY_GROUP_NAME: rest-api-server-group
      - APP_DIR: .
    docker:
      - image: innovatorjapan/awscli:latest
    steps:
      - attach_workspace:
          at: .
      - run: sh /bin/aws-s3-deploy

workflows:
  version: 2
   build-deploy:
    jobs:
    - build
    - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
