# Generated by Django 2.0.2 on 2018-12-16 03:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rest_api_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=20, verbose_name='Training Menu Name')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.PositiveSmallIntegerField(choices=[(25, 25), (50, 50), (100, 100), (200, 200), (400, 400), (800, 800)], verbose_name='Distance for the Training Menu')),
                ('style', models.CharField(choices=[('Fr', 'Fr'), ('Ba', 'Ba'), ('Br', 'Br'), ('Fly', 'Fly'), ('IM', 'IM')], max_length=10, verbose_name='Swim Style for the Training Menu')),
                ('time_circle', models.PositiveSmallIntegerField(verbose_name='Time Circle for the Training Menu')),
                ('how_many_times', models.PositiveSmallIntegerField(verbose_name='How Meny Swim?')),
                ('menu_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api_app.MenuName')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_date', models.DateField(default=django.utils.timezone.now, verbose_name='Date of Training')),
                ('daily_reflecrion', models.CharField(max_length=1000, verbose_name='Reflection for Training')),
                ('self_assessment_score', models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, verbose_name='Your Training Score')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='trainingmenu',
            name='training_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api_app.TrainingProgram'),
        ),
    ]
