# Generated by Django 2.0.2 on 2018-12-16 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api_app', '0002_auto_20181216_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuname',
            name='menu_name',
            field=models.CharField(max_length=50, verbose_name='Training Menu Name'),
        ),
    ]
