# Generated by Django 2.0.2 on 2018-12-17 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api_app', '0003_auto_20181216_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='RapTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_rap', models.PositiveSmallIntegerField()),
                ('rap_time', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ResultTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_order', models.PositiveSmallIntegerField()),
                ('result_time', models.FloatField()),
                ('training_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api_app.TrainingMenu')),
            ],
        ),
        migrations.AddField(
            model_name='raptime',
            name='result_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api_app.ResultTime'),
        ),
    ]
