# Generated by Django 2.0.2 on 2018-12-18 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api_app', '0004_auto_20181217_1244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingprogram',
            old_name='daily_reflecrion',
            new_name='daily_reflection',
        ),
    ]
