# Generated by Django 2.0.2 on 2018-12-22 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api_app', '0005_auto_20181218_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
