# Generated by Django 2.0.2 on 2018-12-22 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api_app', '0006_auto_20181222_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingmenu',
            name='training_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TrainingProgram', to='rest_api_app.TrainingProgram'),
        ),
    ]
