# Generated by Django 2.0.2 on 2018-12-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api_app', '0007_auto_20181222_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image')),
            ],
        ),
    ]
