# Generated by Django 2.0.2 on 2018-12-27 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rest_api_app', '0008_imagetest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(max_length=30, verbose_name='Family Name')),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('birthday', models.DateField(verbose_name='Birthday')),
                ('sex', models.CharField(choices=[('M', 'Man'), ('W', 'Woman'), ('O', 'Other')], max_length=5, verbose_name='Sex')),
                ('profile_image', models.ImageField(upload_to='images', verbose_name='Profile Image')),
                ('style_one', models.CharField(choices=[('Fr', 'Fr'), ('Ba', 'Ba'), ('Br', 'Br'), ('Fly', 'Fly'), ('IM', 'IM')], max_length=5, verbose_name='Style1')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
