# Generated by Django 2.0.2 on 2018-12-29 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api_app', '0009_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingprogram',
            name='training_image',
            field=models.CharField(max_length=10000, null=True, verbose_name='Image base64'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.CharField(max_length=10000, verbose_name='Profile Image'),
        ),
    ]
