# Generated by Django 2.0.2 on 2019-01-05 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api_app', '0011_auto_20181230_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(null=True, verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='family_name',
            field=models.CharField(max_length=30, null=True, verbose_name='Family Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=30, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='http://localhost:8000/image/image/temp_RjtSKGy.png', upload_to='image', verbose_name='Profile Image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(choices=[('M', 'Man'), ('W', 'Woman'), ('O', 'Other')], max_length=5, null=True, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='style_one',
            field=models.CharField(choices=[('Fr', 'Fr'), ('Ba', 'Ba'), ('Br', 'Br'), ('Fly', 'Fly'), ('IM', 'IM')], max_length=5, null=True, verbose_name='Style1'),
        ),
    ]
