# Generated by Django 2.0.2 on 2019-01-05 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api_app', '0012_auto_20190105_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(choices=[('Man', 'Man'), ('Woman', 'Woman'), ('Other', 'Other')], max_length=5, null=True, verbose_name='Sex'),
        ),
    ]
