# Generated by Django 2.0.2 on 2019-01-05 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api_app', '0013_auto_20190105_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='family_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Family Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(blank=True, choices=[('Man', 'Man'), ('Woman', 'Woman'), ('Other', 'Other')], max_length=5, null=True, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='style_one',
            field=models.CharField(blank=True, choices=[('Fr', 'Fr'), ('Ba', 'Ba'), ('Br', 'Br'), ('Fly', 'Fly'), ('IM', 'IM')], max_length=5, null=True, verbose_name='Style1'),
        ),
    ]
