# Generated by Django 2.0.2 on 2019-01-05 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api_app', '0014_auto_20190105_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='image/temp_RjtSKGy.png', upload_to='image', verbose_name='Profile Image'),
        ),
    ]
