# Generated by Django 2.0.2 on 2019-01-06 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api_app', '0015_auto_20190105_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resulttime',
            name='result_time',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='trainingprogram',
            name='daily_reflection',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Reflection for Training'),
        ),
        migrations.AlterField(
            model_name='trainingprogram',
            name='training_image',
            field=models.ImageField(blank=True, null=True, upload_to='image', verbose_name='Training Image'),
        ),
    ]
