# Generated by Django 2.0.2 on 2019-01-06 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api_app', '0016_auto_20190106_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='LapTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_lap', models.PositiveSmallIntegerField()),
                ('lap_time', models.FloatField(default=None, null=True)),
                ('result_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api_app.ResultTime')),
            ],
        ),
        migrations.RemoveField(
            model_name='raptime',
            name='result_time',
        ),
        migrations.DeleteModel(
            name='RapTime',
        ),
    ]
