# Generated by Django 2.0.2 on 2019-01-23 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api_app', '0018_auto_20190123_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingprogram',
            name='self_assessment_score',
            field=models.FloatField(default=3, verbose_name='Your Training Score'),
        ),
    ]
