# Generated by Django 2.0.2 on 2019-02-07 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api_app', '0019_auto_20190123_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingprogram',
            name='daily_reflection',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Reflection for Training'),
        ),
    ]
