# Generated by Django 2.0.2 on 2019-02-07 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api_app', '0021_auto_20190207_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptime',
            name='result_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laptimes', to='rest_api_app.ResultTime'),
        ),
        migrations.AlterField(
            model_name='resulttime',
            name='training_menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resulttimes', to='rest_api_app.TrainingMenu'),
        ),
    ]
